---

- name: Install required system packages
  apt: name="{{ item }}" state=present
  with_items: "{{ magesec__required_packages }}"
  register: magesec_deps_ready

- name: Install required python packages
  when: magesec_deps_ready | success
  pip: name="{{ item }}"
  with_items: "{{ magesec__scanner_packages }}"
  register: magesec_ready

- name: Setting /etc/cron.d config for the scan
  when: (magesec_ready | success)
  template: >
    src="{{ item.src }}"
    dest="{{ item.dest }}"
    owner="{{ item.owner }}"
    group="{{ item.group }}"
    mode="{{ item.mode | default('0700') }}"
  with_items: "{{ magesec__cron_files_to_create }}"

#- debug: msg="{{ auto_update }}"
